name: Update GitHub Projects README

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allow manual trigger
  workflow_dispatch:

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      
      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc jq
      
      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GITHUB_TOKEN" > ./token.txt
          gh auth login --with-token < ./token.txt
          rm ./token.txt
      
      - name: Make script executable
        run: chmod +x ./gh-repos-to-markdown.sh
      
      - name: Set username environment variable
        run: |
          # Hardcode your username here - this avoids API permission issues
          echo "GITHUB_USERNAME=zelhajou" >> $GITHUB_ENV
      
      - name: Run repository markdown generator with environment variable
        env:
          GITHUB_USERNAME: ${{ env.GITHUB_USERNAME }}
        run: ./gh-repos-to-markdown.sh
      
      - name: Display debug stats
        run: |
          if [ -f /tmp/final_stats.txt ]; then
            echo "Stats calculated:"
            cat /tmp/final_stats.txt
          fi
      
      - name: Rename output file to README.md
        run: mv github_repositories_complete.md README.md
      
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet README.md; then
            echo "No changes to commit"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in README.md"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Auto-update README.md with latest repository information"
          git push
