name: Update GitHub Projects README

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Use your personal access token
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # Ensure we fetch complete history
          fetch-depth: 0
        
      - name: Set up GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      
      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc jq
      
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" > ./token.txt
          gh auth login --with-token < ./token.txt
          rm ./token.txt
      
      - name: Make script executable
        run: chmod +x ./gh-repos-to-markdown.sh
      
      - name: Run repository markdown generator
        run: ./gh-repos-to-markdown.sh
      
      - name: Rename output file to README.md
        run: mv github_repositories_complete.md README.md
      
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet README.md; then
            echo "No changes to commit"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in README.md"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push if changes exist
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Auto-update README.md with latest repository information"
          # Use PAT explicitly in the push URL
          git push "https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}
